[package]
name = "benchmark_server"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.0"
quinn = "0.11.6"
rustls = "0.23.23"
rustls-pemfile = "2.2.0"
tokio = { version = "1", features = ["full"] }
