[package]
name = "hw1_client"
version = "0.1.0"
edition = "2024"

[dependencies]
quinn = "0.11.6"
tokio = { version = "1.44.0", features = ["full"] }
rustls = { version = "*", features = ["dangerous_configuration"] }
bincode = "2.0.0"
ring = "0.17.13"
